### PR TITLE
Initial release of adding russian translation for manual

### PR DESCRIPTION
**Pull request by medoed-honey-badger**

### CODE REVIEW

**Comment by WouterJansen** [comment]
Hi, thank you for working on the Russian translation. However, I do not think releasing partial translations early is a good idea. I would recommend first finishing a full translation before we merge it into the main one.

**Comment by medoed-honey-badger** [comment]
Hello!
Maybe then we will transfer it to ru-wip?

I don't have much free time yet, and it would help others to get involved and continue localization

**Comment by medoed-honey-badger** [comment]
?

**Comment by WouterJansen** [comment]
Others can continue localisation through your git fork no? I can make some post here on Github and on our forums/discord to look towards people helping you. But I do not like having partial translations online on the public version.

**Comment by medoed-honey-badger** [comment]
>  I can make some post here on Github and on our forums/discord to look towards people helping you.

It would be great :)

**Pull request closed without merging**
