### PR TITLE
Improving kits structure

### PR DESCRIPTION
**Pull request by UTurista**
Based on #3 I made a few alterations in the Kit chapter structure.

I tried to simplify the explanation by removing the "special/infantry/request-able/spawn-able" division, all kits are now designated by their name.

I've also moved the kit overview to the bottom, since that's not as important as knowing how to get the actual kit.

### CODE REVIEW

**Comment by UTurista** [comment]
Preview: https://realitymod.gitbooks.io/pr-manual/content/v/e398fada6696689fbfacd6f938f33a637a5584dd/en/kits/Kits.html

**Comment by CameI** [comment]
I think those are changes in the right direction, Turista. At times, the structure of the current manual format seems to me more like a good description of PR features and content, but the way I see it, it should aim to act rather as a User's Guide for new players. For this reason, I think it should greatly highlight and prioritize the most gameplay relevant information and to reduce or even omit some of the not so gameplay relevant bits.

If you allow me, I would like to suggest for your consideration some changes to this new version of yours.  How do I go about that? Do I need to make a whole new branch off it, or can you somehow give me writing access to it? As I say, I'm new to GutHub and have no idea.

**Comment by UTurista** [comment]
You need to sync your fork with this repo so you can have a copy of the branch "feature/improving-kits", see [here](https://help.github.com/articles/syncing-a-fork/) or [here](https://gist.github.com/Chaser324/ce0505fbed06b947d962#keeping-your-fork-up-to-date). Once you have it updated, you do your changes and then make your own pull request.

**Comment by UTurista** [comment]
This pull request, #9 , seems better

**Pull request closed without merging**
